os: windows
language: shell
script: 
  - pwd
  - copy /Y ./docs/fix/AddCompilerRT.cmake ./3rdParty/llvm-project/compiler-rt/cmake/Modules/
  - ./scripts/config_llvm_release.bat
  - ./scripts/build_llvm_release.bat
  - cd tsc
  - ./config_tsc_release.bat
  - ./build_tsc_release.bat