os: windows
language: shell
script: 
  - powershell -Command start-process "cmd.exe" "/c prepare_3rdParty.bat release"
  - cd tsc
  - powershell -Command start-process "cmd.exe" "/c config_tsc_release.bat"
  - powershell -Command start-process "cmd.exe" "/c build_tsc_release.bat"