compilers:
  tslang-native:
    type: tarballs
    dir: tslang-{name}
    untar_dir: tslang-ninja-release
    compression: gz
    check_exe: bin/tslang --version
    url: https://github.com/ASDAlexander77/TypeScriptCompiler/releases/download/v{name}/tslang.tar.gz
    targets:
      - 0.0-pre-alpha20

