// --namespace wraps the output and binds each function by its C name with @linkname;
// --strip-prefix shortens the TS names but never the symbol.

#include "ImporterTestHelper.h"

#include "gmock/gmock.h"

using namespace tsbindgen_test;
using testing::Contains;
using testing::HasSubstr;

TEST(Naming, CNamesAreKept)
{
    auto out = text("#define FX_ANSWER 42\nint fx_add(int a, int b);\n");
    EXPECT_EQ(out, "const FX_ANSWER = 42;\ndeclare function fx_add(a: s32, b: s32): s32;\n");
}

TEST(Naming, NamespaceExportsEverythingAndLinksByCName)
{
    tsbindgen::PrintOptions options;
    options.namespaceName = "Fx";
    auto out = generate("#define FX_ANSWER 42\nstruct fx_point { int x; };\nint fx_add(int a, int b);\n"
                        "int fx_sum(int n, ...);\n",
                        options)
                   .text;
    EXPECT_EQ(out, "namespace Fx {\n"
                   "    export const FX_ANSWER = 42;\n"
                   "    export type fx_point = [x: s32];\n"
                   "    @linkname(\"fx_add\") export declare function fx_add(a: s32, b: s32): s32;\n"
                   "    @varargs @linkname(\"fx_sum\") export declare function fx_sum(n: s32): s32;\n"
                   "}\n");
}

TEST(Naming, StripPrefixRenamesDeclarationsAndTheirUses)
{
    tsbindgen::PrintOptions options;
    options.namespaceName = "Fx";
    options.stripPrefix = "fx_";
    auto out = generate("struct fx_point { int x; };\nint fx_len(struct fx_point *p);\nint other(void);\n", options)
                   .text;
    EXPECT_THAT(out, HasSubstr("    export type point = [x: s32];\n"));
    EXPECT_THAT(out, HasSubstr("    @linkname(\"fx_len\") export declare function len(p: Reference<point>): s32;\n"));
    EXPECT_THAT(out, HasSubstr("    @linkname(\"other\") export declare function other(): s32;\n"));
}

TEST(Naming, StripPrefixKeepsTheCNameWhenStrippingWouldBreakIt)
{
    tsbindgen::PrintOptions options;
    options.namespaceName = "Fx";
    options.stripPrefix = "fx_";
    auto out = generate("int len(void);\nint fx_len(void);\nint fx_2d(void);\nint fx_delete(void);\n", options);
    EXPECT_THAT(out.text, HasSubstr("@linkname(\"len\") export declare function len(): s32;"));
    EXPECT_THAT(out.text, HasSubstr("@linkname(\"fx_len\") export declare function fx_len(): s32;"));
    EXPECT_THAT(out.text, HasSubstr("@linkname(\"fx_2d\") export declare function fx_2d(): s32;"));
    EXPECT_THAT(out.text, HasSubstr("@linkname(\"fx_delete\") export declare function delete_(): s32;"));
    EXPECT_THAT(out.warnings, Contains("kept 'fx_len' unstripped: 'len' is taken by 'len'"));
}

TEST(Naming, HeaderLinesComeFirst)
{
    tsbindgen::PrintOptions options;
    options.headerLines = {"Generated by tsbindgen dev (clang 22.1.8); do not edit.", "tsbindgen input.h"};
    EXPECT_EQ(generate("int f(void);\n", options).text,
              "// Generated by tsbindgen dev (clang 22.1.8); do not edit.\n"
              "// tsbindgen input.h\n"
              "\n"
              "declare function f(): s32;\n");
}

// legal C names that TS reserves: the TS name gets a `_`, and @linkname keeps the symbol
TEST(Naming, ReservedWordDeclarationNamesAreEscaped)
{
    auto out = text("int new(void);\nint class(int in);\nstruct export { int x; };\n");
    EXPECT_THAT(out, HasSubstr("@linkname(\"new\") declare function new_(): s32;"));
    EXPECT_THAT(out, HasSubstr("@linkname(\"class\") declare function class_(in_: s32): s32;"));
    EXPECT_THAT(out, HasSubstr("type export_ = [x: s32];"));
}

// an asm label is the symbol the function links as (glibc's __REDIRECT: stat -> stat64)
TEST(Naming, AsmLabelIsTheSymbol)
{
    EXPECT_THAT(text("int f(int x) __asm__(\"real_f\");\n"),
                HasSubstr("@linkname(\"real_f\") declare function f(x: s32): s32;"));
}
