# Default settings for TypeScript Compiler
compilers=&tslang
compilerType=typescript
versionFlag=--version

group.tslang.compilers=tslang_jit_gc:tslang_jit_nogc
compiler.tslang_jit_gc.exe=/home/alex/TypeScriptCompiler/__build/tslang-ninja/bin/tslang
compiler.tslang_jit_gc.sharedlibs=/home/alex/TypeScriptCompiler/__build/tslang-ninja/lib/libTypeScriptRuntime.so
compiler.tslang_jit_gc.name=TypeScript JIT (GC)
compiler.tslang_jit_nogc.exe=/home/alex/TypeScriptCompiler/__build/tslang-ninja/bin/tslang
compiler.tslang_jit_nogc.sharedlibs=
compiler.tslang_jit_nogc.name=TypeScript JIT (No GC)

defaultCompiler=tslang_jit_gc
supportsBinary=false
supportsExecute=true
interpreted=true

