include(${CMAKE_CURRENT_LIST_DIR}/LocateTSLang.cmake)

if(NOT CMAKE_TSLANG_COMPILER OR NOT EXISTS "${CMAKE_TSLANG_COMPILER}")
    locate_tslang_compiler()
    set(CMAKE_TSLANG_COMPILER "${CMAKE_TSLANG_COMPILER}" CACHE FILEPATH "TSLANG compiler" FORCE)
endif()

cmake_path(GET CMAKE_TSLANG_COMPILER PARENT_PATH CMAKE_TSLANG_DIR)

mark_as_advanced(CMAKE_TSLANG_COMPILER)
mark_as_advanced(CMAKE_TSLANG_DIR)

set(CMAKE_TSLANG_SOURCE_FILE_EXTENSIONS ts)
if(NOT WIN32)
    set(CMAKE_TSLANG_OUTPUT_EXTENSION .o)
else()
    set(CMAKE_TSLANG_OUTPUT_EXTENSION .obj)
endif()
set(CMAKE_TSLANG_COMPILER_ENV_VAR "TSLANG")

configure_file(
    ${CMAKE_CURRENT_LIST_DIR}/CMakeTSLANGCompiler.cmake.in
    ${CMAKE_PLATFORM_INFO_DIR}/CMakeTSLANGCompiler.cmake @ONLY)
