name: Test - Release - Linux

on:
#  push:
#    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    branches: [ main ]
  schedule:
    # 8:30 and 18:30 UTC:
    - cron:  '30 8,18 * * *'
env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
#    - name: check disk space
#      run: Get-PSDrive
#      shell: pwsh

    - uses: actions/checkout@v2

    - name: Cache Build 3rd Party
      id: cache-3rd-party
      uses: actions/cache@v2
      with:
        path: __build/llvm-ninja
        key: ${{ runner.os }}-build-llvm-v1

    - name: Cache 3rd Party binaries
      id: cache-3rd-party-binary
      uses: actions/cache@v2
      with:
        path: 3rdParty
        key: ${{ runner.os }}-3rd-party-v1

    - name: Cache 3rd Party binaries - LLVM 13 Release
      id: cache-3rd-party-binary-llvm-13-release
      uses: actions/cache@v2
      with:
        path: llvm_13_release.tgz
        key: ${{ runner.os }}-3rd-party-llvm-13-release-v1

    - name: Delete __Build TS folders
      continue-on-error: true
      run: rm -R ./__build/tsc-ninja-release
      shell: sh

    - name: Create __Build Folders
      run: mkdir -p ./__build/tsc-ninja-release; mkdir -p ./__build/gc-ninja-release
      shell: sh
    
    - name: Download 3rd party - LLVM
      continue-on-error: true
      shell: sh
      if: hashFiles('llvm_13_release.tgz') == ''
      run: curl -L https://www.dropbox.com/s/schmu3qkja0xswu/llvm_13_release.tgz?dl=1 --output llvm_13_release.tgz

    - name: UnZip 3rd party - LLVM
      continue-on-error: false
      shell: sh
      if: hashFiles('llvm_13_release.tgz') != ''
      run: file llvm_13_release.tgz; mkdir -p ./3rdParty/llvm-ninja; tar -xf llvm_13_release.tgz -C ./3rdParty/llvm-ninja/
      #run: file llvm_13_release.tgz; unzip llvm_13_release.tgz -d ./3rdParty/llvm-ninja/

    - name: Download 3rd party source - GC
      continue-on-error: true
      shell: sh
      if: hashFiles('gc-8.0.4.tar.gz') == ''
      run: curl https://www.hboehm.info/gc/gc_source/gc-8.0.4.tar.gz --output gc-8.0.4.tar.gz

    - name: UnZip 3rd party source - GC
      continue-on-error: false
      shell: sh
      if: hashFiles('gc-8.0.4.tar.gz') != ''
      run: tar -xvzf gc-8.0.4.tar.gz -C ./3rdParty/

    - name: Install Ninja
      continue-on-error: false
      shell: sh
      run: sudo apt install ninja-build

#    - name: Install Clang 12
#      continue-on-error: false
#      shell: sh
#      run: sudo apt install clang-12

    - name: Configure GC
      continue-on-error: false
      working-directory: ${{github.workspace}}/__build/gc-ninja-release
      shell: sh
      run: cmake ../../3rdParty/gc-8.0.4 -G "Ninja" -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} -Wno-dev -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DCMAKE_INSTALL_PREFIX=../../3rdParty/gc/release

    - name: Build GC
      continue-on-error: false
      working-directory: ${{github.workspace}}/__build/gc-ninja-release
      shell: sh
      run: cmake --build . --config ${{ env.BUILD_TYPE }} -j 8

    - name: Copy GC
      continue-on-error: false
      working-directory: ${{github.workspace}}/__build/gc-ninja-release
      shell: sh
      run: mkdir -p ../../3rdParty/gc/release/; cp ./lib* ../../3rdParty/gc/release/

    - name: Configure
      continue-on-error: false
      working-directory: ${{github.workspace}}/__build/tsc-ninja-release
      shell: sh
      run: cmake ../../tsc -G "Ninja" -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} -Wno-dev

    - name: Build
      continue-on-error: true
      working-directory: ${{github.workspace}}/__build/tsc-ninja-release
      shell: sh
      run: cmake --build . --config ${{ env.BUILD_TYPE }} -j 8

    - name: Test
      continue-on-error: true
      working-directory: ${{github.workspace}}/__build/tsc-ninja-release
      shell: sh
      # Execute tests defined by the CMake configuration.  
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest -j18 -C ${{ env.BUILD_TYPE }} -T test --output-on-failure -T test --output-on-failure
      
