name: CMake

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    branches: [ main ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Prepare 3rd party
      run: .\prepare_3rdParty.bat

    - name: Configure CMake
      working-directory: ${{github.workspace}}/tsc
      run: .\config_tsc_debug.bat

    - name: Build
      working-directory: ${{github.workspace}}/tsc
      run: .\build_tsc_debug.bat

    - name: Test
      working-directory: ${{github.workspace}}/__build
      # Execute tests defined by the CMake configuration.  
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest -C Debug
      
