name: Create Release/Upload Asset

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build_on_windows:
    name: Create/Upload Release Asset (Windows)
    runs-on: windows-2019
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build project # This would actually build your project, using zip for an example artifact
        run: echo '::set-output name=SELECTED_COLOR::green Build project (Windows)'        

      - name: Cache Build 3rd Party
        id: cache-3rd-party
        uses: actions/cache@v2
        with:
          path: __build/llvm
          key: ${{ runner.os }}-build-llvm-v3

      - name: Cache 3rd Party binaries
        id: cache-3rd-party-binary
        uses: actions/cache@v2
        with:
          path: 3rdParty
          key: ${{ runner.os }}-3rd-party-v3

      - name: Cache 3rd Party binaries - LLVM 13 Release
        id: cache-3rd-party-binary-llvm-13-release
        uses: actions/cache@v2
        with:
          path: llvm_13_release.zip
          key: ${{ runner.os }}-3rd-party-llvm-13-release-v3

      - name: Delete __Build TS folders
        continue-on-error: true
        run: if (Test-Path -Path ".\__build\tsc-release") { Remove-Item -Recurse -Force ".\__build\tsc-release" }
        shell: pwsh

      - name: Create __Build Folders
        run: if (!(Test-Path -Path ".\__build\tsc-release")) { New-Item -ItemType Directory -Force -Path ".\__build\tsc-release" }; if (!(Test-Path -Path ".\__build\llvm\release")) { New-Item -ItemType Directory -Force -Path ".\__build\llvm\release" }; if (!(Test-Path -Path ".\__build\gc-release")) { New-Item -ItemType Directory -Force -Path ".\__build\gc-release" };
        shell: pwsh
      
      - name: Download 3rd party - LLVM
        continue-on-error: true
        shell: pwsh
        if: hashFiles('llvm_13_release.zip') == ''
        run: Invoke-WebRequest -Uri "https://public.am.files.1drv.com/y4m10Qvbrw-g-tUiPxw20oTRpLSp1JoKRxSbg5V395uQFYPyvkVyI6YvDdrT0G5zMDtoF6WljTpDV3hpKszvHdVjCvuLR3ye3OHFSqFzO3PmNl1CBjIE6YcYa8O7QMVTGFIZASpveWikhcsd5qyDe--75g07hg50g7wXAhDl7WXAH1Aiwd_xI3SMimfY8t9ivEVM7cVUyCIZFnN8jWSA_AgjWkP-amlUEg-npWM-_tSbFI" -OutFile "llvm_13_release.zip"

      - name: UnZip 3rd party - LLVM
        continue-on-error: false
        if: hashFiles('llvm_13_release.zip') != ''
        run: Expand-Archive -Path "llvm_13_release.zip" -DestinationPath "3rdParty\llvm\" -Force
        shell: pwsh

      - name: Download 3rd party source - GC
        continue-on-error: true
        shell: pwsh
        if: hashFiles('gc-8.0.4.tar.gz') == ''
        run: Invoke-WebRequest -Uri "https://www.hboehm.info/gc/gc_source/gc-8.0.4.tar.gz" -OutFile "gc-8.0.4.tar.gz"

      - name: Download 3rd party source - GC:Atomic_ops
        continue-on-error: true
        shell: pwsh
        if: hashFiles('libatomic_ops-7.6.10.tar.gz') == ''
        run: Invoke-WebRequest -Uri "https://www.hboehm.info/gc/gc_source/libatomic_ops-7.6.10.tar.gz" -OutFile "libatomic_ops-7.6.10.tar.gz"

      - name: UnZip 3rd party source - GC
        continue-on-error: false
        if: hashFiles('gc-8.0.4.tar.gz') != ''
        run: tar -xvzf gc-8.0.4.tar.gz -C ./3rdParty/
        shell: pwsh

      - name: UnZip 3rd party source - GC:Atomic_ops
        continue-on-error: false
        if: hashFiles('libatomic_ops-7.6.10.tar.gz') != ''
        run: tar -xvzf libatomic_ops-7.6.10.tar.gz -C ./3rdParty/
        shell: pwsh

      - name: Create gc-8.0.4\libatomic_ops Folders
        run: if (!(Test-Path -Path ".\3rdParty\gc-8.0.4\libatomic_ops")) { New-Item -ItemType Directory -Force -Path ".\3rdParty\gc-8.0.4\libatomic_ops" };
        shell: pwsh

      - name: Copy Atomic_ops to GC
        continue-on-error: false
        run:  xcopy  /E /H /C /I /Y ".\3rdParty\libatomic_ops-7.6.10" ".\3rdParty\gc-8.0.4\libatomic_ops"
        shell: pwsh

      - name: Copy fixes to GC
        continue-on-error: false
        run: xcopy  /E /H /C /I /Y ".\docs\fix\gc" ".\3rdParty\gc-8.0.4"
        shell: pwsh

      - name: Configure GC
        continue-on-error: false
        working-directory: ${{github.workspace}}/__build/gc-release
        run: cmake ../../3rdParty/gc-8.0.4 -G "Visual Studio 16 2019" -A x64 -Wno-dev -Denable_threads=ON -Denable_cplusplus=OFF
        shell: pwsh

      - name: Build GC
        continue-on-error: false
        working-directory: ${{github.workspace}}/__build/gc-release
        run: cmake --build . --config ${{ env.BUILD_TYPE }} -j 8
        shell: pwsh

      - name: Copy GC
        continue-on-error: false
        working-directory: ${{github.workspace}}/__build/gc-release
        run:  xcopy /Y .\${{ env.BUILD_TYPE }}\*.* ..\..\3rdParty\gc\release\
        shell: pwsh

      - name: Configure
        continue-on-error: false
        working-directory: ${{github.workspace}}/__build/tsc-release
        run: cmake ../../tsc -G "Visual Studio 16 2019" -A x64 -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} -Wno-dev
        shell: pwsh

      - name: Build
        continue-on-error: false
        working-directory: ${{github.workspace}}/__build/tsc-release
        run: cmake --build . --config ${{ env.BUILD_TYPE }} -j 8
        shell: pwsh

      - name: Test
        working-directory: ${{github.workspace}}/__build/tsc-release
        # Execute tests defined by the CMake configuration.  
        # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
        run: ctest -j18 -C ${{ env.BUILD_TYPE }} -T test --output-on-failure -T test --output-on-failure
        shell: pwsh

      - name: Create Zip of Windows Asset
        working-directory: ${{github.workspace}}/__build
        run: Get-ChildItem -Path .\tsc-release\bin\tsc.exe, .\tsc-release\bin\TypeScriptRuntime.dll, .\gc-release\${{ env.BUILD_TYPE }}\gc-lib.lib | Compress-Archive -DestinationPath ..\tsc.zip
        shell: pwsh

      - name: Archive Zip of Windows Asset
        uses: actions/upload-artifact@v2
        with:
          name: tsc-windows-asset
          path: tsc.zip
          retention-days: 1          
  
  build_on_linux:
    name: Create/Upload Release Asset (Linux)

    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache Build 3rd Party
        id: cache-3rd-party
        uses: actions/cache@v2
        with:
          path: __build/llvm-ninja
          key: ${{ runner.os }}-build-llvm-v3

      - name: Cache 3rd Party binaries
        id: cache-3rd-party-binary
        uses: actions/cache@v2
        with:
          path: 3rdParty
          key: ${{ runner.os }}-3rd-party-v3

      - name: Cache 3rd Party binaries - LLVM 13 Release
        id: cache-3rd-party-binary-llvm-13-release
        uses: actions/cache@v2
        with:
          path: llvm_13_release.tgz
          key: ${{ runner.os }}-3rd-party-llvm-13-release-v3

      - name: Delete __Build TS folders
        continue-on-error: true
        run: rm -R ./__build/tsc-ninja-release
        shell: sh

      - name: Create __Build Folders
        run: mkdir -p ./__build/tsc-ninja-release; mkdir -p ./__build/gc-ninja-release
        shell: sh
      
      - name: Download 3rd party - LLVM
        continue-on-error: true
        shell: sh
        if: hashFiles('llvm_13_release.tgz') == ''
        run: curl -L https://public.am.files.1drv.com/y4mbyNW2o6LXRDl0uZnFRo_x2L35wp33N_9TJIWmjinBdJtj6L7wwy9JpgExcj6wAa_qe7fJta-dYO-219yjXvsfo15O6s2sBiwtZS13RzPUIyN8-yXhA5PapcmKzgTiHHEFhuDGQhWTXANSNMfW21D3YanLGSbgv2ONz8pn-W-3tteLTVDiRvFC6xDffBZCKN9k3zFObOpVmfCD_OkJmLC_714ljdxEgoW3QtsOt1FbCg --output llvm_13_release.tgz

      - name: UnZip 3rd party - LLVM
        continue-on-error: false
        shell: sh
        if: hashFiles('llvm_13_release.tgz') != ''
        run: file llvm_13_release.tgz; mkdir -p ./3rdParty/llvm-ninja; tar -xf llvm_13_release.tgz -C ./3rdParty/llvm-ninja/
        #run: file llvm_13_release.tgz; unzip llvm_13_release.tgz -d ./3rdParty/llvm-ninja/

      - name: Download 3rd party source - GC
        continue-on-error: true
        shell: sh
        if: hashFiles('gc-8.0.4.tar.gz') == ''
        run: curl -L https://www.hboehm.info/gc/gc_source/gc-8.0.4.tar.gz --output gc-8.0.4.tar.gz

      - name: Download 3rd party source - GC:Atomic_ops
        continue-on-error: true
        shell: sh
        if: hashFiles('libatomic_ops-7.6.10.tar.gz') == ''
        run: curl -L https://www.hboehm.info/gc/gc_source/libatomic_ops-7.6.10.tar.gz --output libatomic_ops-7.6.10.tar.gz

      - name: UnZip 3rd party source - GC
        continue-on-error: false
        shell: sh
        if: hashFiles('gc-8.0.4.tar.gz') != ''
        run: tar -xvzf gc-8.0.4.tar.gz -C ./3rdParty/

      - name: UnZip 3rd party source - GC:Atomic_ops
        continue-on-error: false
        shell: sh
        if: hashFiles('libatomic_ops-7.6.10.tar.gz') != ''
        run: tar -xvzf libatomic_ops-7.6.10.tar.gz -C ./3rdParty/

      - name: Copy Atomic_ops to GC
        continue-on-error: false
        shell: sh
        run:  cp -a ./3rdParty/libatomic_ops-7.6.10/ ./3rdParty/gc-8.0.4/libatomic_ops/

      - name: Copy fixes to GC
        continue-on-error: false
        shell: sh
        run: cp -ar ./docs/fix/gc/* ./3rdParty/gc-8.0.4/

      - name: Install Ninja
        continue-on-error: false
        shell: sh
        run: sudo apt install ninja-build

  #    - name: Install Clang 12
  #      continue-on-error: false
  #      shell: sh
  #      run: sudo apt install clang-12

      - name: Configure GC
        continue-on-error: false
        working-directory: ${{github.workspace}}/__build/gc-ninja-release
        shell: sh
        run: cmake ../../3rdParty/gc-8.0.4 -G "Ninja" -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} -Wno-dev -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DCMAKE_INSTALL_PREFIX=../../3rdParty/gc/release -Denable_threads=ON -Denable_cplusplus=OFF

      - name: Build GC
        continue-on-error: false
        working-directory: ${{github.workspace}}/__build/gc-ninja-release
        shell: sh
        run: cmake --build . --config ${{ env.BUILD_TYPE }} -j 8

      - name: Copy GC
        continue-on-error: false
        working-directory: ${{github.workspace}}/__build/gc-ninja-release
        shell: sh
        run: mkdir -p ../../3rdParty/gc/release/; cp ./lib* ../../3rdParty/gc/release/

      - name: Configure
        continue-on-error: false
        working-directory: ${{github.workspace}}/__build/tsc-ninja-release
        shell: sh
        run: cmake ../../tsc -G "Ninja" -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} -Wno-dev

      - name: Build
        continue-on-error: false
        working-directory: ${{github.workspace}}/__build/tsc-ninja-release
        shell: sh
        run: cmake --build . --config ${{ env.BUILD_TYPE }} -j 4

      - name: Test
        continue-on-error: false
        working-directory: ${{github.workspace}}/__build/tsc-ninja-release
        shell: sh
        # Execute tests defined by the CMake configuration.  
        # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
        run: ctest -j18 -C ${{ env.BUILD_TYPE }} -T test --output-on-failure -T test --output-on-failure
        
      - name: Create Tar.GZ of Linux Asset
        working-directory: ${{github.workspace}}/__build
        shell: sh
        run: tar -czvf ../tsc.tar.gz ./tsc-ninja-release/bin/tsc ./tsc-ninja-release/lib/libTypeScriptRuntime.so ./tsc-ninja-release/lib/libTypeScriptRuntime.so.13 ./gc-ninja-release/libgc-lib.a 

      - name: Archive Tar.GZ of Linux Asset
        uses: actions/upload-artifact@v2
        with:
          name: tsc-linux-asset
          path: tsc.tar.gz
          retention-days: 1   

  create_release:
    needs: [build_on_windows, build_on_linux]
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          prerelease: true
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}

  deploy_windows_asset:
    needs: create_release
    name: Upload Release (Windows)
    runs-on: windows-latest
    steps:
      - name: Download Release Asset from Store
        uses: actions/download-artifact@v2
        with:
          name: tsc-windows-asset

      - name: Upload Release Asset (Windows)
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./tsc.zip
          asset_name: tsc.zip
          asset_content_type: application/zip

  deploy_linux_asset:
    needs: create_release
    name: Upload Release (Linux)
    runs-on: ubuntu-latest
    steps:
      - name: Download Release Asset from Store
        uses: actions/download-artifact@v2
        with:
          name: tsc-linux-asset

      - name: Upload Release Asset (Linux)
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./tsc.tar.gz
          asset_name: tsc.tar.gz
          asset_content_type: application/tar+gzip
